FROM postgres:16

# Install pg_cron
RUN apt-get update && \
    apt-get install -y postgresql-16-cron && \
    echo "shared_preload_libraries = 'pg_cron'" >> /usr/share/postgresql/postgresql.conf.sample